package br.com.marceloazevedo.dentist.odonto.api.model

import br.com.marceloazevedo.dentist.odonto.api.converter.LocalDateTimeConverter
import br.com.marceloazevedo.dentist.odonto.api.enum.UF
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.Instant
import java.time.LocalDateTime
import java.util.*

@DynamoDBDocument
data class Address(
        @DynamoDBAutoGeneratedKey
        val id: String? = null,
        @DynamoDBAttribute
        val cep: String,
        @DynamoDBAttribute
        val street: String,
        @DynamoDBAttribute
        val number: String,
        @DynamoDBAttribute
        val city: String,
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        val uf: UF,
        @DynamoDBAttribute
        val complement: String? = null,
        @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
        val createdAt: LocalDateTime = LocalDateTime.now()
)
