package br.com.marceloazevedo.dentist.odonto.api.model

import br.com.marceloazevedo.dentist.odonto.api.converter.LocalDateTimeConverter
import br.com.marceloazevedo.dentist.odonto.api.enum.UF
import br.com.marceloazevedo.dentist.odonto.api.integration.exchange.request.AddressRequest
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDateTime
import java.util.*

@DynamoDBDocument
data class Address(
        @DynamoDBAutoGeneratedKey
        val id: String = UUID.randomUUID().toString(),
        @DynamoDBAttribute
        val cep: String,
        @DynamoDBAttribute
        val street: String,
        @DynamoDBAttribute
        val number: String,
        @DynamoDBAttribute
        val city: String,
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        val uf: UF,
        @DynamoDBAttribute
        val complement: String? = null,
        @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
        val createdAt: LocalDateTime = LocalDateTime.now()
) {
    constructor(addressRequest: AddressRequest?) : this(
            UUID.randomUUID().toString(), addressRequest?.cep!!, addressRequest.street!!, addressRequest.number!!,
            addressRequest.city!!, addressRequest.uf!!, addressRequest.complement, LocalDateTime.now()
    )
}
