package br.com.marceloazevedo.dentist.odonto.api.model

import br.com.marceloazevedo.dentist.odonto.api.converter.LocalDateTimeConverter
import br.com.marceloazevedo.dentist.odonto.api.enum.ContactType
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDateTime

@DynamoDBDocument
data class Contact(
        @DynamoDBAutoGeneratedKey
        val id: String? = null,
        @DynamoDBAttribute
        val name: String,
        @DynamoDBAttribute
        val value: String,
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        val type: ContactType,
        @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
        val createdAt: LocalDateTime = LocalDateTime.now()
)
