package br.com.marceloazevedo.dentist.odonto.api.model

import br.com.marceloazevedo.dentist.odonto.api.converter.LocalDateConverter
import br.com.marceloazevedo.dentist.odonto.api.converter.LocalDateTimeConverter
import br.com.marceloazevedo.dentist.odonto.api.enum.Genre
import br.com.marceloazevedo.dentist.odonto.api.integration.exchange.request.CreateDentistRequest
import br.com.marceloazevedo.dentist.odonto.api.util.toLocalDate
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.*

@DynamoDBTable(tableName = "dentist")
data class Dentist(
        @DynamoDBHashKey @DynamoDBAutoGeneratedKey
        val id: String = UUID.randomUUID().toString(),
        val cro: CRO,
        @DynamoDBAttribute
        val name: String,
        @DynamoDBAttribute
        val cpf: String,
        @DynamoDBAttribute
        val rg: String,
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
        val genre: Genre,
        @DynamoDBTypeConverted(converter = LocalDateConverter::class)
        val birthDate: LocalDate,
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.L)
        val contacts: List<Contact>,
        @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.L)
        val addresses: List<Address>?,
        @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
        val createdAt: LocalDateTime = LocalDateTime.now(),
        @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
        val updatedAt: LocalDateTime? = null
) {
    constructor(createDentist: CreateDentistRequest) : this(
            UUID.randomUUID().toString(), CRO(createDentist.cro), createDentist.name!!, createDentist.cpf!!,
            createDentist.rg!!, createDentist.genre!!, createDentist.birthDate!!.toLocalDate(),
            createDentist.contacts!!.map { Contact(it) },
            if (createDentist.addresses.isNullOrEmpty()) null else createDentist.addresses.map { Address(it) }
    )

    override fun toString(): String {
        return "Dentist(id=$id, cro=$cro, name='$name', cpf='$cpf', rg='$rg', genre=$genre, birthDate=$birthDate, contacts=$contacts, address=$addresses, createdAt=$createdAt, updatedAt=$updatedAt)"
    }
}
